{{- define "deploy_utils.pvolume" }}
{{- if or (not (hasKey .app.harness.deployment.volume "auto")) .app.harness.deployment.volume.auto }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .app.harness.deployment.volume.name }}
  labels:
    app: {{ .app.harness.deployment.name| quote }}
spec:
  resources:
    requests:
      storage: {{ .app.harness.deployment.volume.size }}

  accessModes:
{{- if or (not (hasKey .app.harness.deployment.volume "usenfs")) (not .app.harness.deployment.volume.usenfs) }}
  # ZS: {{ printf "%s-%s" .root.Values.apps.nfsserver.storageClass.name .root.Values.namespace }}
  - ReadWriteOnce
  storageClassName: standard
{{- else }}
  - ReadWriteMany
  storageClassName: {{ printf "%s-%s" .root.Values.namespace .root.Values.apps.nfsserver.storageClass.name }}
{{- end }}
{{- end }}
---
{{- end }}
{{- range $app := .Values.apps }}
    {{- if and $app.harness.deployment.auto $app.harness.deployment.volume }}
---
    {{- include "deploy_utils.pvolume" (dict "root" $ "app" $app) }}
    {{- end }}
{{- end }}