{{- define "deploy_utils.database.mongo" }}
        {{- if .app.harness.database.image_ref }}
        image: {{ index (index .app "task-images") .app.harness.database.image_ref | default ("Image ref not found!" | quote) }}
        {{- else }}
        image: {{ .app.harness.database.mongo.image }}
        {{- end }}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .app.harness.database.user | quote }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .app.harness.database.pass | quote }}
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 6
{{- end }}