apiVersion: v1
appVersion: 2.5.0
description: CloudHarness Helm Chart
maintainers:
- {email: filippo@metacell.us, name: Filippo Ledda}
- {email: zoran@metacell.us, name: Zoran Sinnema}
name: cloud-harness
version: 0.0.1