openapi: 3.0.0
info:
  description: CloudHarness Volumes manager API
  license:
    name: UNLICENSED
  title: Volumes manager API
  version: 0.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: /api
tags:
- description: rest API for Volumes manager
  name: rest

paths:
  /pvc:
    post:
      operationId: pvc_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersistentVolumeClaimCreate'
        description: The Persistent Volume Claim to create.
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type: string
                example: "Saved!"
          description: Save successful.
        "400":
          description: The Persistent Volume Claim already exists.
        "401":
          description: Unauthorized - No authorization token provided.
        "500":
          description: Internal server error.
      security:
      - bearerAuth: []
      summary: Create a Persistent Volume Claim in Kubernetes
      tags:
      - rest
      x-openapi-router-controller: volumemanager.controllers.rest_controller
  /pvc/{name}:
    get:
      operationId: pvc_name_get
      parameters:
      - description: The name of the Persistent Volume Claim to be retrieved
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          minLength: 1
          maxLength: 253
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistentVolumeClaim'
          description: The Persistent Volume Claim.
        "401":
          description: Unauthorized - No authorization token provided.
        "404":
          description: The Persistent Volume Claim was not found.
      security:
      - bearerAuth: []
      summary: Retrieve a Persistent Volume Claim from the Kubernetes repository.
      tags:
      - rest
      x-openapi-router-controller: volumemanager.controllers.rest_controller
components:
  schemas:
    PersistentVolumeClaimCreate:
      example:
        size: 2Gi
        name: pvc-1
      properties:
        name:
          description: Unique name for the Persisten Volume Claim to create.
          example: pvc-1
          type: string
        size:
          description: The size of the Persistent Volume Claim to create.
          example: 2Gi
          type: string
      required:
        - name
        - size
      type: object
    PersistentVolumeClaim:
      example:
        size: 2Gi
        name: pvc-1
        namespace: ch
        accessmode: ReadWriteMany
      properties:
        name:
          description: Unique name for the Persisten Volume Claim
          example: pvc-1
          type: string
        namespace:
          description: The namespace where the Persistent Volume Claim resides in
          example: ch
          type: string
        accessmode:
          description: The accessmode of the Persistent Volume Claim
          example: ReadWriteMany
          type: string
        size:
          description: The size of the Persistent Volume Claim.
          example: 2Gi
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: cloudharness.auth.decode_token
